name: CICD Python Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_USER: dgg32
  DOCKER_IMAGE: gc_biopython_docker

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest

    - name: docker login
      env:
        DOCKER_USER: $DOCKER_USER
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_IMAGE:$(date +%s)

    - name: Docker Push
      run: docker push $DOCKER_USER/$DOCKER_IMAGE
